export const patientData = [
    {
        id: 1,
        name: 'John Doe',
        language: 'ENG',
        urgency: 'T1',
        time: '10:30',
        date: '16-10',
    },
    {
        id: 2,
        name: 'Jane Smith',
        language: 'FR',
        urgency: 'T2',
        time: '14:15',
        date: '17-10',
    },
    {
        id: 3,
        name: 'Alice Johnson',
        language: 'DE',
        urgency: 'T3',
        time: '15:45',
        date: '18-10',
    },
    {
        id: 4,
        name: 'Bob Wilson',
        language: 'ENG',
        urgency: 'T1',
        time: '11:20',
        date: '19-10',
    },
    {
        id: 5,
        name: 'Sarah Brown',
        language: 'FR',
        urgency: 'T2',
        time: '16:50',
        date: '20-10',
    },
    {
        id: 6,
        name: 'Michael Lee',
        language: 'DE',
        urgency: 'T3',
        time: '09:00',
        date: '21-10',
    },
    {
        id: 7,
        name: 'Linda Wilson',
        language: 'ENG',
        urgency: 'T1',
        time: '13:30',
        date: '22-10',
    },
    {
        id: 8,
        name: 'Chris Evans',
        language: 'FR',
        urgency: 'T2',
        time: '15:00',
        date: '23-10',
    },
    {
        id: 9,
        name: 'Karen Johnson',
        language: 'DE',
        urgency: 'T3',
        time: '14:45',
        date: '24-10',
    },
    {
        id: 10,
        name: 'David Clark',
        language: 'ENG',
        urgency: 'T1',
        time: '10:15',
        date: '25-10',
    },
    {
        id: 11,
        name: 'Emily Turner',
        language: 'ENG',
        urgency: 'T1',
        time: '14:45',
        date: '16-10',
    },
    {
        id: 12,
        name: 'Thomas Miller',
        language: 'DE',
        urgency: 'T2',
        time: '16:15',
        date: '17-10',
    },
    {
        id: 13,
        name: 'Sophia Wilson',
        language: 'BE',
        urgency: 'T3',
        time: '09:30',
        date: '18-10',
    },
    {
        id: 14,
        name: 'Ava Martinez',
        language: 'FR',
        urgency: 'T1',
        time: '10:20',
        date: '19-10',
    },
    {
        id: 15,
        name: 'Liam Davis',
        language: 'ENG',
        urgency: 'T2',
        time: '13:50',
        date: '20-10',
    },
    {
        id: 16,
        name: 'Olivia Harris',
        language: 'FR',
        urgency: 'T3',
        time: '17:10',
        date: '21-10',
    },
    {
        id: 17,
        name: 'Ethan White',
        language: 'DE',
        urgency: 'T1',
        time: '10:45',
        date: '22-10',
    },
    {
        id: 18,
        name: 'Mia Johnson',
        language: 'BE',
        urgency: 'T2',
        time: '15:25',
        date: '23-10',
    },
    {
        id: 19,
        name: 'Noah Brown',
        language: 'ENG',
        urgency: 'T3',
        time: '14:00',
        date: '24-10',
    },
    {
        id: 20,
        name: 'Emma Clark',
        language: 'FR',
        urgency: 'T1',
        time: '11:30',
        date: '25-10',
    },
    {
        id: 20,
        name: 'Emma Clark',
        language: 'FR',
        urgency: 'T1',
        time: '11:30',
        date: '25-10',
    },
    {
        id: 18,
        name: 'Mia Johnson',
        language: 'BE',
        urgency: 'T2',
        time: '15:25',
        date: '23-10',
    },
]
