export const patientData = [
    {
        id: 1,
        name: 'John Doe',
        language: 'ENG',
        nationality: 'Belgie',
        urgency: 'T1',
        time: '10:30',
        date: '16-10',
        dateOfBirth: '15-05-1990',
        gender: 'Man',
        allergies: false,
    },
    {
        id: 2,
        name: 'Jane Smith',
        nationality: 'Belgie',
        language: 'FR',
        urgency: 'T2',
        time: '14:15',
        date: '17-10',
        dateOfBirth: '30-12-1985',
        gender: 'Vrouw',
        allergies: true,
    },
    {
        id: 3,
        name: 'Alice Johnson',
        nationality: 'Belgie',
        language: 'DE',
        urgency: 'T3',
        time: '15:45',
        date: '18-10',
        dateOfBirth: '20-09-1978',
        gender: 'Vrouw',
        allergies: true,
    },
    {
        id: 4,
        name: 'Bob Wilson',
        nationality: 'Belgie',
        language: 'ENG',
        urgency: 'T1',
        time: '11:20',
        date: '19-10',
        dateOfBirth: '10-02-1995',
        gender: 'Man',
        allergies: true,
    },
    {
        id: 5,
        name: 'Sarah Brown',
        nationality: 'Belgie',
        language: 'FR',
        urgency: 'T2',
        time: '16:50',
        date: '20-10',
        dateOfBirth: '25-07-1987',
        gender: 'Vrouw',
        allergies: true,
    },
    {
        id: 6,
        name: 'Michael Lee',
        nationality: 'Belgie',
        language: 'DE',
        urgency: 'T3',
        time: '09:00',
        date: '21-10',
        dateOfBirth: '15-11-1992',
        gender: 'Man',
        allergies: false,
    },
    {
        id: 7,
        name: 'Linda Wilson',
        nationality: 'Belgie',
        language: 'ENG',
        urgency: 'T1',
        time: '13:30',
        date: '22-10',
        dateOfBirth: '05-04-1980',
        gender: 'Vrouw',
        allergies: true,
    },
    {
        id: 8,
        name: 'Chris Evans',
        nationality: 'Belgie',
        language: 'FR',
        urgency: 'T2',
        time: '15:00',
        date: '23-10',
        dateOfBirth: '03-09-1998',
        gender: 'Man',
        allergies: true,
    },
    {
        id: 9,
        name: 'Karen Johnson',
        nationality: 'Belgie',
        language: 'DE',
        urgency: 'T3',
        time: '14:45',
        date: '24-10',
        dateOfBirth: '20-06-1993',
        gender: 'Man',
        allergies: true,
    },
    {
        id: 10,
        name: 'David Clark',
        nationality: 'Belgie',
        language: 'ENG',
        urgency: 'T1',
        time: '10:15',
        date: '25-10',
        dateOfBirth: '10-12-1997',
        gender: 'Man',
        allergies: true,
    },
    {
        id: 11,
        name: 'Emily Turner',
        nationality: 'Belgie',
        language: 'ENG',
        urgency: 'T1',
        time: '14:45',
        date: '16-10',
        dateOfBirth: '25-03-1991',
        gender: 'Vrouw',
        allergies: true,
    },
    {
        id: 12,
        name: 'Thomas Miller',
        nationality: 'Belgie',
        language: 'DE',
        urgency: 'T2',
        time: '16:15',
        date: '17-10',
        dateOfBirth: '12-08-1996',
        gender: 'Man',
        allergies: true,
    },
];

export interface Lozenge {
    id: number;
    name: string;
    selected: boolean;
}

export const lozenges: Lozenge[] = [
    { id: 1, name: 'Operatie', selected: false },
    { id: 2, name: 'Oogspoeling', selected: false },
    { id: 3, name: 'Consultaite', selected: false },
    { id: 4, name: 'Operatie', selected: false },
    { id: 5, name: 'Consultaite', selected: false },
    { id: 6, name: 'Oogspoeling', selected: false },
    { id: 7, name: 'Operatie', selected: false },
    { id: 8, name: 'Grote Wondzorg', selected: false },
    { id: 9, name: 'Kleine Brnadwonden', selected: false },
    { id: 10, name: 'Operatie', selected: false },
    { id: 11, name: 'Operatie', selected: false },
    { id: 12, name: 'Consultaite', selected: false },
    { id: 13, name: 'Oogspoeling', selected: false },
    { id: 14, name: 'YOGI', selected: false },
    { id: 15, name: 'Operatie', selected: false },
    { id: 16, name: 'Oogspoeling', selected: false },
    { id: 17, name: 'Operatie', selected: false },
    { id: 18, name: 'Consultaite', selected: false },
    { id: 19, name: 'Oogspoeling', selected: false },
    { id: 20, name: 'YOGI', selected: false },
    { id: 21, name: 'Oogspoeling', selected: false },
];

export const arrayOfParacetamol = [
    'Paracetamol 500mg',
    'Paracetamol 500mg',
    'Paracetamol 500mg',
    'Paracetamol 500mg',
    'Paracetamol 500mg',
    'Paracetamol 500mg',
];
