export const patientData = [
    {
        id: 1,
        name: 'John Doe',
        language: 'ENG',
        urgency: 'T1',
        time: '10:30',
        date: '16-10',
        dateOfBirth: '1990-05-15',
        gender: 'male',
    },
    {
        id: 2,
        name: 'Jane Smith',
        language: 'FR',
        urgency: 'T2',
        time: '14:15',
        date: '17-10',
        dateOfBirth: '1985-12-30',
        gender: 'female',
    },
    {
        id: 3,
        name: 'Alice Johnson',
        language: 'DE',
        urgency: 'T3',
        time: '15:45',
        date: '18-10',
        dateOfBirth: '1978-09-20',
        gender: 'female',
    },
    {
        id: 4,
        name: 'Bob Wilson',
        language: 'ENG',
        urgency: 'T1',
        time: '11:20',
        date: '19-10',
        dateOfBirth: '1995-02-10',
        gender: 'male',
    },
    {
        id: 5,
        name: 'Sarah Brown',
        language: 'FR',
        urgency: 'T2',
        time: '16:50',
        date: '20-10',
        dateOfBirth: '1987-07-25',
        gender: 'male',
    },
    {
        id: 6,
        name: 'Michael Lee',
        language: 'DE',
        urgency: 'T3',
        time: '09:00',
        date: '21-10',
        dateOfBirth: '1992-11-15',
        gender: 'male',
    },
    {
        id: 7,
        name: 'Linda Wilson',
        language: 'ENG',
        urgency: 'T1',
        time: '13:30',
        date: '22-10',
        dateOfBirth: '1980-04-05',
        gender: 'female',
    },
    {
        id: 8,
        name: 'Chris Evans',
        language: 'FR',
        urgency: 'T2',
        time: '15:00',
        date: '23-10',
        dateOfBirth: '1998-09-03',
        gender: 'male',
    },
    {
        id: 9,
        name: 'Karen Johnson',
        language: 'DE',
        urgency: 'T3',
        time: '14:45',
        date: '24-10',
        dateOfBirth: '1993-06-20',
        gender: 'male',
    },
    {
        id: 10,
        name: 'David Clark',
        language: 'ENG',
        urgency: 'T1',
        time: '10:15',
        date: '25-10',
        dateOfBirth: '1997-12-10',
        gender: 'male',
    },
    {
        id: 11,
        name: 'Emily Turner',
        language: 'ENG',
        urgency: 'T1',
        time: '14:45',
        date: '16-10',
        dateOfBirth: '1991-03-25',
        gender: 'male',
    },
    {
        id: 12,
        name: 'Thomas Miller',
        language: 'DE',
        urgency: 'T2',
        time: '16:15',
        date: '17-10',
        dateOfBirth: '1996-08-12',
        gender: 'male',
    },
]

export const lozenges = [
    { id: 1, name: 'HALL' },
    { id: 2, name: 'RICO' },
    { id: 3, name: 'STRE' },
    { id: 4, name: 'FISH' },
    { id: 5, name: 'CEPA' },
    { id: 6, name: 'LUDE' },
    { id: 7, name: 'VICK' },
    { id: 8, name: 'ROBI' },
    { id: 9, name: 'SMIT' },
    { id: 10, name: 'SURE' },
    { id: 11, name: 'PINE' },
    { id: 12, name: 'SMIT' },
    { id: 13, name: 'TRAD' },
    { id: 14, name: 'YOGI' },
    { id: 15, name: 'CHLO' },
    { id: 16, name: 'CEPA' },
]
